name: Tests
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1.0', '3.2.0', '3.3.0-preview2']
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install gems
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
